name: ParamSpider Scan

on:
  workflow_dispatch:
    inputs:
      target_domain:
        description: "Domain to scan"
        required: true
        default: "example.com"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev git

    - name: Clone and Install ParamSpider
      run: |
        git clone https://github.com/devanshbatham/paramspider.git
        cd paramspider
        pip install .

    - name: Run ParamSpider
      run: |
        paramspider -d ${{ github.event.inputs.target_domain }}

    - name: Show Results
      run: |
        cat results/${{ github.event.inputs.target_domain }}.txt || echo "No output file found"
